apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    name: istio-system
    istio-injection: disabled
    app.kubernetes.io/name: istio-system
    app.kubernetes.io/part-of: istio-system